-- Initial schema for the ordering context.
CREATE TABLE orders (
    id          UUID         PRIMARY KEY,
    customer_id UUID         NOT NULL,
    currency    VARCHAR(3)   NOT NULL,
    status      VARCHAR(20)  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL,
    version     BIGINT       NOT NULL DEFAULT 0
);

CREATE TABLE order_lines (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          UUID          NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id        UUID          NOT NULL,
    sku               VARCHAR(64)   NOT NULL,
    unit_price_amount NUMERIC(19,4) NOT NULL,
    quantity          INTEGER       NOT NULL
);

CREATE INDEX idx_order_lines_order_id ON order_lines (order_id);
CREATE INDEX idx_orders_customer_id   ON orders (customer_id);
